spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.tqbnaofknpvtxeuklfzb&password=YOURPASSWORD
spring.datasource.username=postgres.tqbnaofknpvtxeuklfzb
spring.datasource.password=Dhr2chB1vXDzaASZ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false